import "./globals.css";
import Navbar from "./components/custom/Navbar";
import Footer from "./components/custom/Footer";

export const metadata = {
  title: "glint",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <Navbar />
      <body>
        {children}
      </body>
      <Footer />
    </html>
  );
}
